#!/bin/bash
diff-lines() {
        local path=
        local pathOld=
        local line=
        while read; do
                esc=$'\033'
                if [[ $REPLY =~ ---\ (a/)?.* ]]; then
                        continue
                elif [[ $REPLY =~ \+\+\+\ (b/)?([^[:blank:]$esc]+).* ]]; then
                        path=${BASH_REMATCH[2]}
                elif [[ $REPLY =~ @@\ -[0-9]+(,[0-9]+)?\ \+([0-9]+)(,[0-9]+)?\ @@.* ]]; then
                        line=${BASH_REMATCH[2]}
                elif [[ $REPLY =~ ^($esc\[[0-9;]+m)*([\ +-]) ]]; then

                        if [ "$path" != "$pathOld" ]; then
                                echo -e "\n\n$path:$line:$REPLY"
                        else
                                echo "$path:$line:$REPLY"
                        fi

                        if [[ ${BASH_REMATCH[2]} != - ]]; then
                                ((line++))
                        fi
                        pathOld=$path
                fi
        done
}

if [ "$1" != "" ]; then		#可查看单个文件的差异（方法：git-diff-lines  xxx.c）
        git diff --no-index  --  "$1" | diff-lines
else
        git diff output1.csv output2.csv  | diff-lines
fi


#git diff -U0 | diff-lines output1.csv output2.csv